generic-service:
  nameOverride: hmpps-unused-deductions-listener
  productId: "DPS014"
  serviceAccountName: hmpps-adjustments
  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-unused-deductions-listener
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-unused-deductions-listener-cert
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-unused-deductions-listener:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    sqs-adjustments-unused-deductions-secret:
      HMPPS_SQS_QUEUES_UNUSEDDEDUCTIONS_QUEUE_NAME: "sqs_queue_name"
    sqs-adjustments-unused-deductions-dlq-secret:
      HMPPS_SQS_QUEUES_UNUSEDDEDUCTIONS_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

  retryDlqCronjob:
    enabled: true

generic-prometheus-alerts:
  targetApplication: hmpps-unused-deductions-listener
