---
# Per environment values which override defaults in hmpps-unused-deductions-listener/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-unused-deductions-listener-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    ADJUSTMENTS_API_URL: https://adjustments-api-preprod.hmpps.service.justice.gov.uk
    CALCULATERELEASEDATES_API_URL: https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
