---
# Per environment values which override defaults in hmpps-unused-deductions-listener/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-unused-deductions-listener-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    ADJUSTMENTS_API_URL: https://adjustments-api-dev.hmpps.service.justice.gov.uk
    CALCULATERELEASEDATES_API_URL: https://calculate-release-dates-api-dev.hmpps.service.justice.gov.uk
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  sqsAlertsQueueNames:
    - "farsight-devs-dev-hmpps_unused_deductions_queue"
    - "farsight-devs-dev-hmpps_unused_deductions_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: legacy-replacement-alerts-non-prod
